name: Craftory-Utils
version: ${project.version}
main: ${mainClass}
api-version: 1.16
author: ${author}
website: https://craftory.studio/

commands:
  calculate:
    description: Calcualation based commands
  calc:
    description: An alias for calculate (Calculation based commands)

permisions:
  craftory-utils.calculate:
    default: op
  craftory-utils.calculate.saveLocations:
    default: op
  craftory-utils.calculate.usePlayerLocations:
    default: op
  craftory-utils.calculate.managePlayersSavedLocations:
    default: op