name: Craftory-Calculate
version: ${project.version}
main: ${mainClass}
api-version: 1.16
author: ${author}
website: https://craftory.studio/

commands:
  calculate:
    description: Craftory-Calculate commands.
  calc:
    description: Craftory-Calculate commands.
  c:
    description: Craftory-Calculate commands.

permisions:
  craftory-calculate:
    default: op
  craftory-calculate.save:
    default: op